gd/apps/article/urls.py
# _*_ coding:utf-8 _*_
from django.conf.urls import url

from .views import ArticleView,ArticleDetailView,AddFavView,AddCommentsView

urlpatterns = [
    url(r'^list$', ArticleView.as_view(), name='article_list'),
    url(r'^detail/(?P<article_id>\d+)/$',ArticleDetailView.as_view(), name='article_detail'),
    #收藏文章
    url(r'^add_fav/$',AddFavView.as_view(), name='add_fav'),
    url(r'^add_comment/$',AddCommentsView.as_view(), name='add_comment'),
]

gd/apps/operation/urls.py
# _*_ coding:utf-8 _*_
from django.conf.urls import url, include

from .views import WriteArticleView,TestEditorView,EditArticleView,DeleteArticleView


urlpatterns = [
    url(r'^write/$',WriteArticleView.as_view(),name='operation_write'),
    # 修改文章
    url(r'^editarticle/(?P<edit_article_id>\d+)/$', EditArticleView.as_view(), name='operation_edit'),
    url(r'^testeditor/$',TestEditorView.as_view(),name='test_editor'),
    url(r'^delete/$',DeleteArticleView.as_view(),name='operation_delete'),
]

gd/apps/users/urls.py
# _*_ coding:utf-8 _*_
from django.conf.urls import url, include

from .views import UserDetailView,UserInfoView,UserListView,EditUserMessage,AddFavView,UploadImageView,UploadSurfaceView

urlpatterns = [
    url(r'^list$', UserListView.as_view(), name='user_list'),
    #用户信息
    url(r'^detail/(?P<user_id>\d+)/$', UserDetailView.as_view(), name='user_detail'),
    url(r'^info/$',UserInfoView.as_view(),name='user_info'),
    url(r'^editmymessage/$',EditUserMessage.as_view(),name='edit_message'),
    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),
    #用户头像上传
    url(r'image/upload/$',UploadImageView.as_view(),name='image_upload'),
    #用户封面页上传
    url(r'surface/upload/$',UploadSurfaceView.as_view(),name='surface_upload'),
]

gd/extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

gd/gd/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
import xadmin

from gd.settings import MEDIA_ROOT
from users.views import LoginView,LogoutView,IndexView


urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$',TemplateView.as_view(template_name='wellcomepage.html'),name='wellcomepage'),
    url(r'^index/$',IndexView.as_view(),name='index'),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),

    #apps url
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^operation/',include('operation.urls',namespace='operation')),

    #
    # url(r'^success/',SuccessView.as_view(),name='success'),
    # url(r'^failed/',FailedView.as_view(),name='failed'),

    # 配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
]

#全局404页面配置
handler404 = 'users.views.page_not_found'
#全局500页面配置
handler500 = 'users.views.page_error'

gd/extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

gd/templates/editarticle.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}修改文章 - F-ZTH{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/simditor.css' %}"/>
    {#     <link href="css/blog.css" rel="stylesheet">#}
    <style>
        #img_file {
            display: none;
        }

    </style>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/module.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/hotkeys.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/uploader.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/simditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/validate.js' %}"></script>

    <script>


        $('#img_file').change(function () {
            loadImg();
        })

        function loadImg() {
            var file = $(".img_btn").find("input")[0].files[0];
            console.log(file)
            var reader = new FileReader();
            var imgFile;
            reader.onload = function (e) {
                imgFile = e.target.result;
                console.log(imgFile);
                $("#image").attr('src', imgFile);
            };
            reader.readAsDataURL(file);
        }

        {#             --------------------------------------------------------------------------------------------------#}
{#        $('#jsEditArticleBtn').on('click', function () {#}
{##}
{#            var _self = $(this),#}
{#                $jsEditArticleForm = $('#jsEditArticleForm')#}
{#            verify = verifySubmit(#}
{#                [#}
{#                    {id: '#edittitle', tips: Dml.Msg.epNickName, require: true}#}
{#                ]#}
{#            );#}
{#            if (!verify) {#}
{#                return;#}
{#            }#}
{#            $.ajax({#}
{#                cache: false,#}
{#                type: "POST",#}
{#                dataType: 'json',#}
{#                url: "{% url 'operation:operation_edit' %}",#}
{#                data: $jsEditArticleForm.serialize(),#}
{#                async: true,#}
{#                beforeSend: function (xhr, settings) {#}
{#                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");#}
{#                },#}
{##}
{#                success: function (data) {#}
{#                    if (data.title) {#}
{#                        _showValidateError($('#edittitle'), data.title);#}
{#                    } else if (data.detail) {#}
{#                        _showValidateError($('.editdetail'), data.detail);#}
{#                    } else if (data.status == "failure") {#}
{#                        Dml.fun.showTipsDialog({#}
{#                            title: '保存失败',#}
{#                            h2: data.msg#}
{#                        });#}
{#                    } else if (data.status == "success") {#}
{#                        Dml.fun.showTipsDialog({#}
{#                            title: '保存成功',#}
{#                            h2: '文章保存成功！'#}
{#                        });#}
{#                        setTimeout(function () {#}
{#                            window.location.href = window.location.href;#}
{#                        }, 1500);#}
{#                    }#}
{#                },#}
{#                complete: function (XMLHttpRequest) {#}
{#                    _self.val("保存");#}
{#                    _self.removeAttr("disabled");#}
{#                }#}
{#            });#}
{#        });#}

    </script>
{% endblock %}
{% block content %}
    <div class="blog-header">
        <br>
    </div>
    <!-- /.row -->
    <div class="container">
        <hr style="padding:0%;margin:2%;" class="featurette-divider">
        <div class="">
            <form class="perinform center-block" id="" autocomplete="off" method="post" enctype="multipart/form-data"
                  action="{% url 'operation:operation_edit' edit_article.id %}">
                <div style="text-align: center;">
                    {% if edit_article.image %}
                    <img name="fengmiantu" id="image" src="{{ MEDIA_URL }}{{ edit_article.image }}"/>
                    {% else %}
                        <img name="fengmiantu" id="image" src="{% static 'images/default_surface.jpg' %}" alt="封面图">
                    {% endif %}
                </div>
                <br>
                <div class="text-center">
                    <label class="btn btn-default btn-lg img_btn" style="color: #8590a6;">
                        <input type="file" id="img_file" name="image" accept=".jpg,.png" hidden/>修改文章封面</label>
                </div>
                <h3>题目</h3>
                <input type="text" id="edittitle" class="form-control" name="title" value="{{ edit_article.title }}"/>

                <h3>正文</h3>
                <textarea id="editdetail" name="detail" class="form-control" rows="30">{{ edit_article.detail }}</textarea>
                <br>
                <h4 name="id" style="display: none">{{ article.id }}</h4>
                <center>
                    <div class="btn_wrap">
                        <button type="button" class="btn btn-default btn-lg">
                            <a href="{% url 'article:article_list' %}" style="color:#8590a6;">取消</a>
                        </button>
                        <button class="btn_finish btn btn-primary btn-lg" id="jsEditArticleBtn"
                                style="background-color:#096c47;">完成
                        </button>
                    </div>
                </center>
                {% csrf_token %}
            </form>
            <hr>
        </div>
    </div>


{% endblock %}

gd/templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/fzth.ico' %}">

    <title>首页 - F-ZTH</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
     <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/justified-nav.css' %}">



</head>
<!-- NAVBAR
================================================== -->

<body style="background-color: #f6f6f6">
<!-- 固定导航条 -->
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false"
                    aria-controls="navbar">
                <span class="sr-only">From Zero to Hero</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a style="color:#ffffff;" class="navbar-brand" href="/">F-ZTH</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li {% if request.path|slice:'6' == '/index' %}class="active"{% endif %}>
                    <a href="{% url 'index' %}">
                        <span class="glyphicon glyphicon-home"></span> 首页</a>
                </li>
                <li {% if request.path|slice:'13' == '/article/list' %}class="active"{% endif %}>
                    <a href="{% url 'article:article_list' %}">
                        <span class="glyphicon glyphicon-align-justify"></span> 文章列表</a>
                </li>
                <li {% if request.path|slice:'10' == '/user/list' %}class="active"{% endif %}>
                    <a href="{% url 'user:user_list' %}"><span class="glyphicon glyphicon-user"></span> 用户列表</a>
                </li>
                <li {% if request.path|slice:'16' == '/operation/write' %}class="active"{% endif %}>
                    <a href="{% url 'operation:operation_write' %}"><span class="glyphicon glyphicon-edit"></span>
                        写文章</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">

                <div class="navbar-form navbar-left" role="search">
                    <div class="btn-group">
                        <button id="jsSelectOption" type="button" class="btn btn-default dropdown-toggle "
                                data-toggle="dropdown" data-value="article">
                            文章
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu" id="jsSelectMenu">
                            <li data-value="article"><a href="#">文章</a></li>
                            <li data-value="user"><a href="#">用户</a></li>
                        </ul>
                    </div>
                    <div class="form-group">
                        <input id="search_keywords" type="text" class="form-control" placeholder="请输入搜索内容">
                        <button id="jsSearchBtn" type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </div>
                </div>


                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                        {#                         <li><a href="{% url 'user:user_info' %}"><img width="20" height="20" src="/static/images/fzth.ico"/>&nbsp;{{ request.user.username }}#}
                        {#                         </a></li>#}
                        <li class="dropdown">
                            <a href="{% url 'user:user_info' %}" class="dropdown-toggle" data-toggle="dropdown"
                               role="button" aria-haspopup="true" aria-expanded="false">
                                <img width="20" height="20"
                                     src="{{ MEDIA_URL }}{{ request.user.image }}"/>&nbsp;{{ request.user.username }}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'user:user_detail' request.user.id %}">进入个人主页</a>
                                </li>
                                <li>
                                    <a href="{% url 'user:user_info' %}">进入个人中心</a>
                                </li>
                            </ul>
                        </li>

                        <li><a href="{% url 'logout' %}">退出</a></li>
                    {% else %}
                        <li><a href="#"><span class="glyphicon glyphicon-user"></span> 注册</a></li>
                        <li><a href="/login/"><span class="glyphicon glyphicon-log-in"></span> 登录</a></li>
                    {% endif %}


                </ul>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>
<!-- Marketing messaging and featurettes
================================================== -->

<div class="container marketing" >
     <!-- Jumbotron -->
    <div class="blog-header">
            <!-- <h3 class="blog-title">&nbsp;发呆</h3> -->
            <br>
        </div>

 <!-- Jumbotron -->
      <div class="jumbotron">
          <h1>{{ showtime }}</h1>
            <p>{{ shownong }}</p>
{#        <h1>想感受一下本网站的魅力吗？</h1>#}
{#        <p class="lead">试试体验帐号吧！</p>#}
{#                  <p>帐号：<code>test@test.com</code></p>#}
{#                <p>密码：<code>testtest123</code></p>#}
          <h2>说明：</h2>

                        <p>1.文章副标题为文章关键词</p>
                        <p>2.文章下方进度条为情感分析评分条（绿色为正评分，红色为负评分）</p>
        <p><a class="btn btn-lg btn-success" href="{% url 'login' %}" role="button">Get started today</a></p>
      </div>


    <!-- FOOTER -->
    <footer class="footer">
        <p class="pull-right">
            <a href="#">回到顶部</a>
        </p>
        <p>&copy; 2018 广东工业大学, 自动化学院. &middot;
            <a href="#">物联网工程</a> &middot;
            <a href="#">2014级4班</a>
        </p>
    </footer>
</div>
<!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->

<!-- Placed at the end of the document so the pages load faster -->
{#<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>#}
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="../../assets/js/vendor/holder.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

<script>
    //顶部搜索栏搜索方法
    function search_click() {
        var type = $('#jsSelectOption').attr('data-value'),
            keywords = $('#search_keywords').val(),
            request_url = '';
        if (keywords == "") {
            return
        }
        if (type == "article") {
            request_url = "/article/list?keywords=" + keywords
        } else if (type == "user") {
            request_url = "/user/list?keywords=" + keywords
        }
        window.location.href = request_url
    }

    //顶部搜索栏搜索按钮事件
    $('#jsSelectOption').on('click', function () {
        var $jsSelectMenu = $('#jsSelectMenu');
        if ($jsSelectMenu.css('display') == 'block') return;
        $jsSelectMenu.addClass('dis');
    });
    $('#jsSelectMenu > li').on('click', function () {
        var searchType = $(this).attr('data-value'),
            searchName = $(this).text(),
            $jsSelectOption = $('#jsSelectOption');
        $jsSelectOption.attr('data-value', searchType).text(searchName);
        $(this).parent().removeClass('dis');
    });
    $(document).on('click', function (e) {
        if (e.target != $('#jsSelectOption')[0] && e.target != $('#jsSelectMenu')[0]) {
            $('#jsSelectMenu').removeClass('dis');
        }
    });


    $('#jsSearchBtn').on('click', function () {
        search_click()
    });
    //搜索表单键盘事件
    $("#search_keywords").keydown(function (event) {
        if (event.keyCode == 13) {
            $('#jsSearchBtn').trigger('click');
        }
    });

</script>


</body>

</html>

gd/templates/success.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Success!{% endblock %}
{% block content %}
    <br><br><br><br><br><br><br>
    <div class="container marketing">
        <div class="container text-center">
            <div style="text-align: center;">
                <img name="fengmiantu" class="img-circle" src="{% static 'images/LOGO.png' %}" width="140"
                     height="140"/>
            </div>

            <div class="blog-header" >
                <h1 class="blog-title">文章发表成功</h1>
                <p class="lead blog-description">请返回文章列表页</p>
            </div>
            <div class="text-center">
                <button class="btn btn-default btn-lg">
                    <a href="{% url 'article:article_list' %}">回到列表</a>
                </button>
            </div>
        </div>
    </div>
    <br><br><br><br><br>
    <hr>
{% endblock %}